#### 1.导入numpy库并简写为np 
(提示: import … as …)

In [1]:
import numpy as np

#### 2.打印numpy的版本及配置说明
(提示: np.__version__, np.show_config)

In [2]:
print(np.__version__)
np.show_config()

<module 'numpy.version' from 'F:\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
<function show at 0x000002B15B5A17B8>


#### 3.创建一个长度为10的空向量
(提示: np.zeros)

In [4]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.如何找到任何一数组的内存大小?
(提示:size, itemsize)

In [6]:
a.size * a.itemsize

NameError: name 'a' is not defined

#### 5. 如何从命令中找到numpy的add函数的说明文档 (提示np.info)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6. 创建一个长度为10并且除了第五个值为1的空向量

In [9]:
a=np.empty(10)
a[4]=1
a

array([6.23042070e-307, 1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
       1.00000000e+000, 1.11261162e-306, 1.69119330e-306, 7.56599128e-307,
       1.42410974e-306, 2.56761491e-312])

#### 7. 创建一个值域范围从10到49的向量
(提示:np.arange)

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.反转一个向量(从头开始依次进行反转) 
(提示array[::-1])

In [ ]:
b=a[::-1]

#### 9. 创建一个3x3并且值从0到8的矩阵
(提示 reshape)

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. 创建一个 10x10 的随机数组并找到它的最大值和最小值
(提示: min, max)

In [13]:
data = np.random.randn(10,10)
np.max(data)
np.min(data)

-2.48363649621942

#### 11.  创建一个长度为30的随机向量并找到它的平均值
(提示: mean)

In [14]:
data=np.random.randn(30)
np.mean(data)

-0.049451896499712114

#### 12. 对一个5x5的随机矩阵做归一化
(提示: (x-min)/(max - min)

In [15]:
data = np.random.randn(10,10)
xa=np.max(data)
xi=np.min(data)
(data-xi)/(xa-xi)

array([[0.22574436, 0.02995792, 0.57171427, 0.41536219, 0.37940874,
        0.45841046, 0.51026553, 0.44456449, 0.34375794, 0.10896565],
       [0.50057058, 0.4404338 , 0.20568721, 0.64231043, 0.7276372 ,
        0.58209274, 0.14475646, 0.65546949, 0.4125586 , 0.67013918],
       [0.41554046, 0.75010397, 0.52642126, 0.50409881, 0.59050167,
        0.78603658, 0.85084142, 0.83632322, 0.5411276 , 0.5204712 ],
       [0.78742837, 0.22737837, 0.42898708, 0.76681768, 0.35978664,
        0.86218767, 0.58650293, 0.81994169, 0.52347691, 0.4042966 ],
       [0.47396862, 0.31883012, 0.        , 0.34003884, 0.53513844,
        0.29317065, 0.36723735, 0.20569745, 0.26845305, 0.44101842],
       [0.63239911, 0.68491457, 0.64407228, 0.57147496, 0.38982743,
        0.79940039, 0.40582665, 0.67935171, 0.40382254, 0.20754059],
       [0.6588761 , 0.67069434, 0.60030511, 0.53726237, 0.16858419,
        0.45792521, 0.40722308, 0.837059  , 0.40801019, 0.54575986],
       [0.83138275, 0.06736804, 0.8215072

#### 13. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
(提示 np.dot)

In [17]:
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)
a.dot(b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 14. 在给定标量时, 如何找到数组中最接近标量的值?
(提示:argmin)

In [18]:
a=np.arange(15)
a[np.abs(a-10).argmin()]


10

#### 15.如何找到一个数组中出现频率最高的值?
(提示: np.bincount, argmax)

In [32]:
a=np.arange(50)
a[1:10]=10
np.bincount(a).argmax()


10

#### 16. 如何找到一个数组的第n个最大值?
(np.argsort)

In [ ]:
X=np.argsort()
X[n]

#### 17. 如何通过滑动窗口计算一个数组的平均数?
(提示 np.cumsum)

In [33]:
#能看懂，不太会
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
